[package]
name = "lspweb"
version = "0.1.0"
authors = ["Tom Jakubowski <tom@crystae.net>"]
edition = "2018"

[dependencies]
warp = "0.1.20"
lsp-types = "0.61.0"
crossbeam = "0.7"
serde = "1.0"
serde_json = "1.0"
env_logger = "0.7.0"
log = "0.4.8"
tera = "1.0.0-beta.16"
